#!/bin/bash -e

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh

NAME=aesdserver
DIR=/root
PIDFILE=/var/run/$NAME.pid
DAEMON=/bin/aesdsocket
DAEMON_ARGS="-d"
STOP_SIGNAL=INT
USER=root
LOG=/var/log/$NAME.log

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

do_start(){
    start-stop-daemon -S -x $DAEMON -- $DAEMON_ARGS
}

do_stop(){
    start-stop-daemon -K -x $DAEMON -s $STOP_SIGNAL
}

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
        do_start
        echo "."
        ;;
  stop)
        echo -n "Stopping daemon: "$NAME
        do_stop
        echo "."
        ;;
  *)
        echo "Usage: "$1" {start|stop}"
        exit 1
esac

exit 0